from typing import Protocol

from domain.entity.stream_entity import StreamSession, Timestamp
from domain.entity.inf_game_entity import InfPlayData


class PlayRecordingPresenter(Protocol):
    def stream_started(self, session: StreamSession[InfPlayData]) -> None: ...
    def stream_ended(self, session: StreamSession[InfPlayData]) -> None: ...
    def timestamp_added(self, session: StreamSession[InfPlayData], timestamp: Timestamp[InfPlayData]) -> None: ...
    def timestamp_updated(self, session: StreamSession[InfPlayData], timestamp: Timestamp[InfPlayData]) -> None: ...
