from typing import Protocol

from domain.entity.stream_entity import StreamSession, Timestamp


class PlayRecordingPresenter(Protocol):
    def stream_started(self, session: StreamSession) -> None: ...
    def stream_ended(self, session: StreamSession) -> None: ...
    def timestamp_added(self, session: StreamSession, timestamp: Timestamp) -> None: ...
    def timestamp_updated(self, session: StreamSession, timestamp: Timestamp) -> None: ...
