name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Build applications
        run: bash build.bash

      - name: Create zip
        run: powershell -c Compress-Archive -Path "dist/InfTimeStamper/*" -DestinationPath dist/InfTimeStamper.zip -Force

      - name: Create release and upload zip
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/InfTimeStamper.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
